#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
#
    # Enable/Disable show mode on statusline
    enable_statusline_mode = true

    # left sections of statusline
    statusline_left_sections = [
       'winnr',
       # 'major mode',
       'filename',
       # 'fileformat',
       # 'minor mode lighters',
       'version control info',
       'search status'
    ]
    # right sections of statusline
    statusline_right_sections = [
       'cursorpos',
       'date',
       'time'
    ]

    # 'winnr' window number
    # 'syntax checking'
    # 'filename' file name
    # 'fileformat' file format
    # 'major mode'
    # 'minor mode lighters'
    # 'cursorpos' cursor position
    # 'percentage' content range
    # 'date' date
    # 'time' time
    # 'whitespace' line number with trailing space at the end
    # 'battery status' battery status
    # 'input method' input method
    # 'search status' search index
    bootstrap_before = "myspacevim#before" 
    bootstrap_after = "myspacevim#after"   

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "VersionControl"
  enable-gtm-status = true

[[layers]]
  name = "denite"

[[layers]]
  name = "lang#c"
  
[[layers]]
  name = "lang#python"
  python_file_head = [
      '#!/usr/bin/python3',
      '# -*- coding: utf-8 -*-',
      '# by zhen.xiao, xiaozisheng2008@qq.com',
      ''
  ]
  enable_typeinfo = true

[[layers]]
  name = "lsp"
  filetypes = [
    "c",
    "cpp",
    "python"
  ]
  # [layers.override_cmd]
    # c = "clangd" # default
    # cpp = "clangd" # default

# [[layers]]
  # name = "cscope"

[[layers]]
  name = "gtags"
  gtagslabel = "ctags"

[[layers]]
  name = "git"
  git-plugin = "fugitive"

# [[layers]]
# name = "games"


[[layers]]
  name = "default"

[[layers]]
  name = "chinese"
  vim_help_language = "cn"

[[custom_plugins]]
 name = "907th/vim-auto-save"
 merged = false
